var express = require('express')
var router = express.Router()
const optionController = require('../../controllers/api/OptionproductController')
const verifyToken = require('../../Middlewares/JwtAuthMiddleware')
router.get('/list', optionController.list)
router.get('/getAlls', optionController.getAlls)
router.get('/getAllParent', optionController.getAllParent)
router.get('/getAllChild', optionController.getAllChild)
router.get('/getAll', optionController.getAll)
router.get('/show/:id', optionController.show)
router.post('/store', optionController.store)
router.post('/update/:id', optionController.update)
router.post('/remove/:id', optionController.remove)
router.post('/checkHome', optionController.checkHome)
router.post('/checkFocus', optionController.checkFocus)
router.get('/getDataUrl', optionController.getDataUrl)
module.exports = router
