var mongoose = require('mongoose')
var Schema = mongoose.Schema
var OrderSchema = new Schema({
    sort_id: { type: Number, default: 0 },
    name: { type: String, default: '' },
    firstname: { type: String, default: '' },
    lastname: { type: String, default: '' },
    code: { type: String, default: '' },
    type_payment: { type: Number, default: 0  },
    qty: { type: Number, default: 0  },
    price: { type: Number, default: 0  },
    totalPriceShip: { type: Number, default: 0 },
    totalPrice: { type: Number, default: 0 },
    totalPriceAll: { type: Number, default: 0 },
    totalOrder: { type: Number, default: 0 },
    totalQty: { type: Number, default: 0  },
    totalWidth: { type: Number, default: 0  },
    totalHeight: { type: Number, default: 0  },
    totalLong: { type: Number, default: 0  },
    totalWeight: { type: Number, default: 0  },
    totalEpay: { type: Number, default: 0 },
    id_product: { type: String, default: '' },
    arr_id_product: { type: Array },
    items: { type: Array },
    nameReceive: { type: String, default: '' },
    nameCustomer: { type: String, default: '' },
    phoneCustomer: { type: String, default: '' },
    addressCustomer: { type: String, default: '' },
    emailCustomer: { type: String, default: '' },
    countryCustomer: { type: Number, default: 0 },
    provinceCustomer: { type: Number, default: 0 },
    districtCustomer: { type: Number, default: 0 },
    wardCustomer: { type: Number, default: 0 },
    streetCustomer: { type: Number, default: 0 },
    note: { type: String, default: '' },
    datetime: { type: String, default: ''},
    created_at: { type: String, default: ''},
    updated_at: { type: String, default: ''},
    status: { type: Number, default: 0},
    textStatus: { type: String, default: '' },
    user_id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
    },
    user_id_o: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
    },
    payments: { type: Number, default: 0 },
    live: { type: Number, default: 0 },
    id_npp_parent: { type: String, default: '' },
    p_npp_parent: { type: Number, default: 0 },
    id_npp: { type: String, default: '' },
    p_npp: { type: Number, default: 0 },
    id_tdl: { type: String, default: '' },
    p_tdl: { type: Number, default: 0 },
    id_dl: { type: String, default: '' },
    p_dl: { type: Number, default: 0 },
    id_ctv: { type: String, default: '' },
    p_ctv: { type: Number, default: 0 },
    id_ctv_parent: { type: String, default: '' },
    p_ctv_parent: { type: Number, default: 0 },
    id_tv: { type: String, default: '' },
    p_tv: { type: Number, default: 0 },
    tracking: { type: String, default: '' },
    discount: { type: Number, default: 0},
    commission: { type: Number, default: 0 },
    create_at: { type: Date },
    update_at: { type: Date, default: Date.now },
})
module.exports = mongoose.model('Order', OrderSchema);
